version: "1.0"
info:
  model: int-scaffold
packages:
- name: AerazghProject
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  version: "2.0"
  gitServerName: RAHS_IBMBitbucket_shared
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: rahulsingh68
  gitBranch: master
services:
- serviceName: project.aerazgh.integrations:bitbucketfs
  packages:
  - name: AerazghProject
    version: "1.0"
  - name: upperfspackage
    version: "2.0"
- serviceName: UpperFSPackage:upperfs
  packages:
  - name: upperfspackage
    version: "2.0"
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
